from setuptools import setup
setup(
	name="rfGengou",
	version="0.4",
	description="Translate A.D. to Regnal year, and other in Japanese.",
	url="https://github.com/hATrayflood/rfGengou",
	author="hATrayflood",
	author_email="h.rayflood@gmail.com",
	license="The MIT License (MIT)",
	long_description="Detail is needed to written in Japanese. visit github. https://github.com/hATrayflood/rfGengou",
	classifiers=(
		"Development Status :: 4 - Beta",
		"Environment :: Console",
		"Intended Audience :: Developers",
		"License :: OSI Approved :: MIT License",
		"Natural Language :: Japanese",
		"Programming Language :: Python",
		"Programming Language :: Python :: 2",
		"Programming Language :: Python :: 3",
		"Topic :: Office/Business",
		"Topic :: Sociology :: Genealogy",
		"Topic :: Sociology :: History",
		"Topic :: Software Development :: Libraries :: Python Modules",
		"Topic :: Text Processing :: Filters",
	),
	py_modules=["rfGengou"],
	scripts=['rfgengou', 'rfgengou.bat', 'rfGengouCmd.py'],
)
